export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCEED = 'SIGNUP_SUCCEED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const SIGNIN_REQUEST = 'GET_SIGNIN_REQUEST';
export const SIGNIN_SUCCEED = 'GET_SIGNIN_SUCCEED';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCEED = 'LOGOUT_SUCCEED';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const SHOW_MESSAGE = 'SHOW_MESSAGE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCEED = 'GET_USER_SUCCEED';
export const GET_USER_FAILED = 'GET_USER_FAILED';